name: ai_core_os_v3
description: AI Core OS V3 - Neural Engine
publish_to: "none"

version: 3.0.0+300

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Storage
  shared_preferences: ^2.3.2

  # AI
  speech_to_text: ^6.6.2
  flutter_tts: ^4.2.3

  # Security
  local_auth: ^2.1.7
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
